name: Verify licenses

on:
  workflow_call:
    secrets:
      gh_token:
        required: true
    inputs:
      ruby:
        description: "Set up Ruby environment"
        required: false
        default: false
        type: boolean
      node:
        description: "Set up Node environment"
        required: false
        default: false
        type: boolean

permissions:
  contents: write
  pull-requests: write

jobs:
  licensed:
    runs-on: ubuntu-latest

    # always skip
    if: false

    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.gh_token }}

      - uses: gjtorikian/actions/setup-languages@main
        with:
          ruby: ${{ inputs.ruby }}
          node: ${{ inputs.node }}

      - name: Download license script
        run: |
          curl -o $PWD/script/licenses.sh https://raw.githubusercontent.com/gjtorikian/actions/refs/heads/main/script/licenses
          chmod +x $PWD/script/licenses.sh

      - name: Run license verify
        id: check_verify
        shell: bash
        run: |
          $PWD/script/licenses.sh --verify && true

          if [ $? -eq 0 ] ; then
            echo "All licenses are up to date!"
          else
            $PWD/script/licenses.sh --update && true

            if git diff-index --quiet HEAD --; then
              echo "There was an error generating files! Try running script/licenses --verify locally to see what's wrong."
              exit 1
            else
              echo "Licenses updated successfully!"
            fi
          fi

          rm $PWD/script/licenses.sh

      - name: Commit licenses
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "[auto-license]: Update license information"
          commit_user_name: gjtorikian-bot
          commit_user_email: 246872175+gjtorikian-bot@users.noreply.github.com
          commit_author: gjtorikian-bot <246872175+gjtorikian-bot@users.noreply.github.com>
